"""Curated medical-grade material catalog with engineering properties and standards."""

from ..models.materials import Material


MEDICAL_MATERIALS_CATALOG: list[Material] = [
    Material(
        material_id="MAT_PEBAX_7233",
        name="Pebax 7233 SA 01 MED",
        common_trade_names=["Pebax 72D", "Arkema Pebax MED"],
        family="polymer",
        category="Polyether Block Amide (TPE-A)",
        density_g_cm3=1.01,
        tensile_strength_mpa=52.0,
        yield_strength_mpa=38.0,
        elastic_modulus_mpa=510.0,
        flexural_modulus_mpa=480.0,
        elongation_at_break_pct=380.0,
        shore_hardness="72D",
        temperature_min_c=-40.0,
        temperature_max_c=105.0,
        manufacturing_methods=["Extrusion", "Injection Molding", "Overmolding", "Catheter Reflow"],
        sterilization_compatibility={
            "EtO": "Compatible (Standard)",
            "Gamma": "Compatible (up to 50 kGy)",
            "E-beam": "Compatible",
            "Autoclave": "Not Recommended (Hydrolysis risk)",
            "VHP": "Compatible"
        },
        chemical_resistance=["Saline", "Dilute Acids", "Lipids", "Blood"],
        iso_10993_biocompatibility_reference="ISO 10993-4 (Hemocompatibility), ISO 10993-5 (Cytotoxicity)",
        typical_medical_applications=["Catheter shafts", "Angioplasty balloon tubing", "Dilators"],
        source="Arkema Medical Technical Datasheet Pebax MED",
        source_reference="Arkema Technical Data Sheet Rev 4.2 / MatWeb ID: 78921",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_PEBAX_3533",
        name="Pebax 3533 SA 01 MED",
        common_trade_names=["Pebax 35D", "Soft Catheter Tip Resin"],
        family="polymer",
        category="Polyether Block Amide (TPE-A)",
        density_g_cm3=1.01,
        tensile_strength_mpa=28.0,
        yield_strength_mpa=12.0,
        elastic_modulus_mpa=32.0,
        flexural_modulus_mpa=28.0,
        elongation_at_break_pct=550.0,
        shore_hardness="35D",
        temperature_min_c=-40.0,
        temperature_max_c=85.0,
        manufacturing_methods=["Extrusion", "Reflow Bonding", "Overmolding"],
        sterilization_compatibility={
            "EtO": "Compatible (Standard)",
            "Gamma": "Compatible (up to 25 kGy)",
            "E-beam": "Compatible",
            "Autoclave": "Not Recommended",
            "VHP": "Compatible"
        },
        chemical_resistance=["Saline", "Alcohols (short contact)", "Blood"],
        iso_10993_biocompatibility_reference="ISO 10993-5 (Cytotoxicity), ISO 10993-10 (Sensitization)",
        typical_medical_applications=["Atraumatic catheter distal tips", "Flexible strain reliefs"],
        source="Arkema Medical Polymers",
        source_reference="Arkema Pebax 3533 SA01 MED TDS",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_PTFE_EXTRUDED",
        name="Medical Grade PTFE (Polytetrafluoroethylene)",
        common_trade_names=["Teflon", "FluoroMed PTFE", "Zeus Sub-Lite-Wall"],
        family="polymer",
        category="Fluoropolymer",
        density_g_cm3=2.16,
        tensile_strength_mpa=25.0,
        yield_strength_mpa=14.0,
        elastic_modulus_mpa=450.0,
        flexural_modulus_mpa=400.0,
        elongation_at_break_pct=300.0,
        shore_hardness="55D",
        temperature_min_c=-200.0,
        temperature_max_c=260.0,
        manufacturing_methods=["Paste Extrusion", "Ram Extrusion", "Compression Molding", "Machining"],
        sterilization_compatibility={
            "EtO": "Compatible",
            "Gamma": "Not Recommended (Polymer chain scission)",
            "E-beam": "Not Recommended",
            "Autoclave": "Compatible (High Temp Resistant)",
            "VHP": "Compatible"
        },
        chemical_resistance=["Universal chemical inertness", "All clinical solvents", "Lipids", "Concentrated Acids"],
        iso_10993_biocompatibility_reference="USP Class VI, ISO 10993-1 Full Systemic Toxicity",
        typical_medical_applications=["Catheter inner lumen liners", "Low-friction introducer sheaths", "Grafts"],
        source="Zeus Industrial Products Medical White Paper",
        source_reference="Zeus Medical Grade PTFE Specifications Guide 2025",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_TPU_PELLETHANE_80A",
        name="Pellethane 2363-80AE TPU",
        common_trade_names=["Pellethane 80A", "Lubrizol Medical TPU"],
        family="polymer",
        category="Thermoplastic Polyurethane (TPU)",
        density_g_cm3=1.13,
        tensile_strength_mpa=36.0,
        yield_strength_mpa=8.5,
        elastic_modulus_mpa=25.0,
        flexural_modulus_mpa=22.0,
        elongation_at_break_pct=600.0,
        shore_hardness="80A",
        temperature_min_c=-40.0,
        temperature_max_c=90.0,
        manufacturing_methods=["Extrusion", "Injection Molding", "Solvent Casting"],
        sterilization_compatibility={
            "EtO": "Compatible",
            "Gamma": "Compatible (up to 35 kGy)",
            "E-beam": "Compatible",
            "Autoclave": "Not Recommended",
            "VHP": "Compatible"
        },
        chemical_resistance=["Saline", "Dilute Alcohol", "Blood", "Body Fluids"],
        iso_10993_biocompatibility_reference="USP Class VI, ISO 10993 Hemocompatibility",
        typical_medical_applications=["Vascular access tubing", "IV catheters", "Pinch valves"],
        source="Lubrizol Life Science Health",
        source_reference="Lubrizol Pellethane 2363-80AE Technical Bulletin",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_PP_MEDICAL",
        name="Medical Polypropylene (Purell HP570M)",
        common_trade_names=["Purell PP", "Medical Grade PP", "Polypropylene Copolymer"],
        family="polymer",
        category="Polyolefin",
        density_g_cm3=0.905,
        tensile_strength_mpa=34.0,
        yield_strength_mpa=31.0,
        elastic_modulus_mpa=1450.0,
        flexural_modulus_mpa=1400.0,
        elongation_at_break_pct=12.0,
        shore_hardness="70D",
        temperature_min_c=0.0,
        temperature_max_c=125.0,
        manufacturing_methods=["Injection Molding", "Blow Molding", "Extrusion"],
        sterilization_compatibility={
            "EtO": "Compatible",
            "Gamma": "Radiation-stabilized grades only",
            "E-beam": "Compatible (stabilized)",
            "Autoclave": "Compatible (121°C)",
            "VHP": "Compatible"
        },
        chemical_resistance=["Water", "Saline", "Alcohols", "Weak Acids", "Weak Bases"],
        iso_10993_biocompatibility_reference="European Pharmacopoeia 3.1.6, USP Class VI, ISO 10993-5",
        typical_medical_applications=["Syringe barrels", "Plungers", "Luer connectors", "Needle hubs"],
        source="LyondellBasell Purell Medical Polymers",
        source_reference="LyondellBasell TDS Purell HP570M",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_PC_MAKROLON_RX",
        name="Makrolon Rx1805 Polycarbonate",
        common_trade_names=["Makrolon Med", "Lexan HP", "Optical Polycarbonate"],
        family="polymer",
        category="Polycarbonate (PC)",
        density_g_cm3=1.20,
        tensile_strength_mpa=68.0,
        yield_strength_mpa=62.0,
        elastic_modulus_mpa=2350.0,
        flexural_modulus_mpa=2300.0,
        elongation_at_break_pct=110.0,
        shore_hardness="85D",
        temperature_min_c=-40.0,
        temperature_max_c=135.0,
        manufacturing_methods=["Injection Molding", "Machining", "Extrusion"],
        sterilization_compatibility={
            "EtO": "Compatible",
            "Gamma": "Compatible (special lipid/radiation grades)",
            "E-beam": "Compatible",
            "Autoclave": "Compatible (limited cycles 121°C)",
            "VHP": "Compatible"
        },
        chemical_resistance=["Saline", "Aqueous solutions", "Lipid-resistant grades available"],
        iso_10993_biocompatibility_reference="ISO 10993-1, USP Class VI",
        typical_medical_applications=["Luer lock fittings", "Stopcocks", "Dialysis filter housings", "Fluid manifolds"],
        source="Covestro Medical Polycarbonates",
        source_reference="Covestro Makrolon Rx1805 TDS",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_PEEK_OPTIMA",
        name="PEEK-OPTIMA LT1",
        common_trade_names=["PEEK Optima", "Invibio Medical PEEK"],
        family="polymer",
        category="Polyetheretherketone (PEEK)",
        density_g_cm3=1.30,
        tensile_strength_mpa=98.0,
        yield_strength_mpa=92.0,
        elastic_modulus_mpa=3700.0,
        flexural_modulus_mpa=3900.0,
        elongation_at_break_pct=40.0,
        shore_hardness="88D",
        temperature_min_c=-50.0,
        temperature_max_c=250.0,
        manufacturing_methods=["Injection Molding", "CNC Precision Machining", "Extrusion", "Medical FDM/SLS"],
        sterilization_compatibility={
            "EtO": "Compatible",
            "Gamma": "Compatible (>50 kGy)",
            "E-beam": "Compatible",
            "Autoclave": "Compatible (Repeated steam autoclave 134°C)",
            "VHP": "Compatible"
        },
        chemical_resistance=["Outstanding organic solvent and lipid resistance", "Inert to sterilizing agents"],
        iso_10993_biocompatibility_reference="ISO 10993 Implantable Device Master File (FDA MAF 359)",
        typical_medical_applications=["Surgical instrument shafts", "Endoscopic components", "Implantable cages", "Rigid connectors"],
        source="Invibio Biomaterial Solutions",
        source_reference="Invibio PEEK-OPTIMA Material Property Guide 2025",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_SS_316L",
        name="Surgical Stainless Steel 316L (ASTM F138)",
        common_trade_names=["SS316L", "Medical Stainless Steel", "1.4404"],
        family="metal",
        category="Austenitic Stainless Steel",
        density_g_cm3=8.00,
        tensile_strength_mpa=580.0,
        yield_strength_mpa=290.0,
        elastic_modulus_mpa=193000.0,
        flexural_modulus_mpa=193000.0,
        elongation_at_break_pct=40.0,
        shore_hardness="95 HRB",
        temperature_min_c=-200.0,
        temperature_max_c=450.0,
        manufacturing_methods=["Tube Drawing", "CNC Swiss Machining", "Laser Cutting", "Metal 3D Printing (DMLS)"],
        sterilization_compatibility={
            "EtO": "Compatible",
            "Gamma": "Compatible",
            "E-beam": "Compatible",
            "Autoclave": "Compatible (Infinite steam cycles)",
            "VHP": "Compatible"
        },
        chemical_resistance=["High pitting and crevice corrosion resistance in saline and physiological fluids"],
        iso_10993_biocompatibility_reference="ASTM F138 / ISO 5832-1 Surgical Implant Standards",
        typical_medical_applications=["Hypodermic needle cannulas", "Catheter stylets", "Guide wire cores", "Luer lock pins"],
        source="ASTM International Medical Standards",
        source_reference="ASTM F138 Standard Specification for Wrought 18Cr-14Ni-2.5Mo Stainless Steel",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_NITINOL_SUPERELASTIC",
        name="Nitinol Superelastic Alloy (ASTM F2063)",
        common_trade_names=["NiTi Alloy", "Shape Memory Nitinol", "SE508"],
        family="metal",
        category="Nickel-Titanium Shape Memory Alloy",
        density_g_cm3=6.45,
        tensile_strength_mpa=1050.0,
        yield_strength_mpa=560.0,
        elastic_modulus_mpa=75000.0,  # Effective plateau 28-40 GPa, elastic ~75 GPa
        flexural_modulus_mpa=65000.0,
        elongation_at_break_pct=15.0,
        shore_hardness="60 HRC",
        temperature_min_c=-20.0,
        temperature_max_c=60.0,
        manufacturing_methods=["Precision Micro-Tube Drawing", "Laser Cutting", "Shape Setting Heat Treatment"],
        sterilization_compatibility={
            "EtO": "Compatible",
            "Gamma": "Compatible",
            "E-beam": "Compatible",
            "Autoclave": "Compatible",
            "VHP": "Compatible"
        },
        chemical_resistance=["Excellent corrosion resistance via titanium oxide passivation layer"],
        iso_10993_biocompatibility_reference="ASTM F2063 Standard for Medical Instruments and Implants",
        typical_medical_applications=["Vascular guidewires", "Self-expanding stents", "Catheter braided reinforcements", "Biopsy graspers"],
        source="Memry Corporation / SAES Getters Nitinol Technical Specs",
        source_reference="ASTM F2063-18 Standard / Nitinol Property Handbook",
        data_retrieval_date="2026-01-10"
    ),
    Material(
        material_id="MAT_SILICONE_LSR",
        name="Medical Silicone LSR 4350",
        common_trade_names=["Silbione LSR", "Medical Liquid Silicone", "NuSil Med"],
        family="elastomer",
        category="Platinum-Cured Liquid Silicone Rubber",
        density_g_cm3=1.12,
        tensile_strength_mpa=9.5,
        yield_strength_mpa=3.0,
        elastic_modulus_mpa=3.8,
        flexural_modulus_mpa=3.5,
        elongation_at_break_pct=720.0,
        shore_hardness="50A",
        temperature_min_c=-60.0,
        temperature_max_c=200.0,
        manufacturing_methods=["Liquid Injection Molding (LIM)", "Compression Molding", "Extrusion"],
        sterilization_compatibility={
            "EtO": "Compatible",
            "Gamma": "Compatible (up to 25 kGy)",
            "E-beam": "Compatible",
            "Autoclave": "Compatible (Steam sterilizable)",
            "VHP": "Compatible"
        },
        chemical_resistance=["Water", "Body fluids", "Oils", "Alcohols"],
        iso_10993_biocompatibility_reference="ISO 10993-5 (Cytotoxicity), ISO 10993-10, USP Class VI",
        typical_medical_applications=["Syringe plunger elastomeric seal stoppers", "Drainage tubes", "Gaskets", "Needleless injection valves"],
        source="Elkem Silicones Healthcare",
        source_reference="Silbione LSR 4350 Product Data Sheet",
        data_retrieval_date="2026-01-10"
    )
]
